### ISSUE TITLE
DS permission error after Ubuntu 2004 upgrade 

### ISSUE THREAD

**Issue by boeggild** [GhostWriters/DockSTARTer#897]
**Describe the bug**

After upgrading to Ubuntu 20.04, ds will run once then spit out errors after that. If I remove /tmp/dockstarter.log it will work.

**To Reproduce**

Run sudo DS once and exit
Run sudo DS again and i will fail with a permission issue

**Screenshots**

**System**
(please complete the following information):

- OS: Ubuntu
- Version : 2004
![ds](https://user-images.githubusercontent.com/10573732/80072789-061da600-8547-11ea-9839-0ee77655ce69.png)

**Additional context**

**Comment by nemchik** [comment]
```bash
sudo chown $USER:$USER /tmp/dockstarter.log
```

This should fix the issue more permanently. The script tries to do this for you, but in some odd cases it cannot.

**Comment by nemchik** [comment]
Also FYI, DS does not yet officially support 20.04 because it is not yet supported by `docker-ce`.

Note the lack of a `focal` folder as of writing https://download.docker.com/linux/ubuntu/dists/

**Comment by trolley** [comment]
> ```shell
> sudo chown $USER:$USER /tmp/dockstarter.log
> ```
> 
> This should fix the issue more permanently. The script tries to do this for you, but in some odd cases it cannot.

I upgraded before I read these closed issues, but it's working for me using the eoan docker version, but I still get the permission error on `/tmp/dockstarter.log` even if I make sure the ownership is correct, and even if I open the permissions up to `777`.
